import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from "@/components/shared/header";

const inter = Inter({
   subsets: ['latin'],
   variable: '--font-inter',
   weight: ['200', '300', '400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
   title: 'yamakasi',
   description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="en">
      <body className={inter.className}>
         <Header />
         <main className="min-h-screen max-w-[1440px] overflow-y-auto mx-auto">
            {children}
         </main>
      </body>
      </html>
   )
}
